### ISSUE TITLE
control.componet.htm. Debe mostrar el nombre no el Id.

### ISSUE THREAD

**Issue by mammam** [Landaluza/kamishibai#6]
control.componet.html linea69

<td>{{control.idLineaEnvasado}}</td>

Debe mostrar el nombre no el Id

**Comment by mammam** [comment]
![Logo](https://user-images.githubusercontent.com/1251915/62836885-79f17a00-bc68-11e9-812d-6cdcd3cb6e0d.png)

**Comment by jlopezjuy** [comment]
Corregido en ultimo commit: 762aad3c03ac5233207cb0258aa1cc68a0cd0e17
